### ISSUE TITLE
Increase score on pub.dev

### ISSUE THREAD

**Issue by magnussp** [deriegle/dart-airtable#5]
Not sure if I should have done a PR for this but seemed excessive with 3 PR's in 2days ;)

@deriegle I noticed that you can quite easily increase the score of your library on [pub.dev](https://pub.dev/packages/dart_airtable/score) with two simple changes.

1. Make sure the link in the README is **https** instead of http
2. Write a description in pubspec that is at least 60 characters long.

✌️

**Comment by deriegle** [comment]
@magnussp those are great call outs. I'd love to increase the score, so I'll try to fix both of those. Thanks!!

**Comment by deriegle** [comment]
Finally got around to updating this. Thanks!
